### ISSUE TITLE
Can you fix it for firefox browser? :-)

### ISSUE THREAD

**Issue by mowtschan** [Seiichi-Yahiro/rubiks-cube#1]
<img width="740" alt="Bildschirmfoto 2019-07-24 um 11 10 22" src="https://user-images.githubusercontent.com/20609205/61780926-b8cba700-ae03-11e9-9b63-3b8b30a5c432.png">

**Comment by Seiichi-Yahiro** [comment]
Fixed the rendering. Animations still behave strangely though and I'm not sure how to fix that right now.

**Comment by mowtschan** [comment]
Nice! Thanks! 
P.S.: I have no issues with animations what you mentioned.
<img width="719" alt="Bildschirmfoto 2019-07-24 um 12 11 52" src="https://user-images.githubusercontent.com/20609205/61785572-46ab9000-ae0c-11e9-89b0-3fa6f9a22423.png">

**Comment by mowtschan** [comment]
Ok, now I see what you mean.
